name: flutter_advance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
